// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using transporte.src.shared.context;

#nullable disable

namespace transporte.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410215502_RelacionesErd")]
    partial class RelacionesErd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("transporte.src.modules.assignment_role.Infrastructure.entity.AssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("assignment_role", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.audit_log.Infrastructure.entity.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("json")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("json")
                        .HasColumnName("old_values");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("char(36)")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("table_name");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.auth_credentials.Infrastructure.entity.AuthCredentialsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("email");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_attempts");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("auth_credentials", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.auth_sessions.Infrastructure.entity.AuthSessionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_token");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.bids.Infrastructure.entity.BidsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)")
                        .HasColumnName("driver_id");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)")
                        .HasColumnName("load_id");

                    b.Property<Guid>("StatusBidsId")
                        .HasColumnType("char(36)")
                        .HasColumnName("status_bids_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LoadId");

                    b.HasIndex("StatusBidsId");

                    b.HasIndex("VehicleId");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.chat_messages.Infrastructure.entity.ChatMessagesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("char(36)")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_content");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("sender_id");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("SenderId");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.chat_participants.Infrastructure.entity.ChatParticipantsEntity", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("char(36)")
                        .HasColumnName("chat_room_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at");

                    b.HasKey("ChatRoomId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("chat_participants", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.chat_rooms.Infrastructure.entity.ChatRoomsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("chat_rooms", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.cities_municipalities.Infrastructure.entity.CitiesMunicipalitiesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("StateRegionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("state_region_id");

                    b.HasKey("Id");

                    b.ToTable("cities_municipalities", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.city_pricing_rules.Infrastructure.entity.CityPricingRulesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("base_price");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("city_id");

                    b.Property<string>("RuleJson")
                        .HasColumnType("json")
                        .HasColumnName("rule_json");

                    b.HasKey("Id");

                    b.ToTable("city_pricing_rules", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.companies_status.Infrastructure.entity.CompaniesStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("companies_status", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.company_documents.Infrastructure.entity.CompanyDocumentsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<Guid>("DocumentStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("document_status_id");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<Guid>("TypeDocumentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("type_document_id");

                    b.HasKey("Id");

                    b.ToTable("company_documents", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.company_vehicles.Infrastructure.entity.CompanyVehiclesEntity", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("CompanyId", "VehicleId");

                    b.ToTable("company_vehicles", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.countries.Infrastructure.entity.CountriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("iso_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.credit_transactions.Infrastructure.entity.CreditTransactionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreditWalletId")
                        .HasColumnType("char(36)")
                        .HasColumnName("credit_wallet_id");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("transaction_type_id");

                    b.HasKey("Id");

                    b.HasIndex("CreditWalletId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("credit_transactions", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.credit_wallet.Infrastructure.entity.CreditWalletEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("balance");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_update");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("credit_wallet", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.dispute_status.Infrastructure.entity.DisputeStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dispute_status", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.disputes.Infrastructure.entity.DisputesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DisputeStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("dispute_status_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("ReasonDisputesId")
                        .HasColumnType("char(36)")
                        .HasColumnName("reason_disputes_id");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.ToTable("disputes", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.document_category.Infrastructure.entity.DocumentCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("document_category", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.documents_customers.Infrastructure.entity.DocumentsCustomersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("customer_id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("document_number");

                    b.Property<Guid>("DocumentStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("document_status_id");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<Guid>("TypeDocumentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("type_document_id");

                    b.HasKey("Id");

                    b.ToTable("documents_customers", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.documents_drivers.Infrastructure.entity.DocumentsDriversEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("document_number");

                    b.Property<Guid>("DocumentStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("document_status_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)")
                        .HasColumnName("driver_id");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<Guid>("TypeDocumentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("type_document_id");

                    b.HasKey("Id");

                    b.ToTable("documents_drivers", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.documents_status.Infrastructure.entity.DocumentsStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("documents_status", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.documents_vehicles.Infrastructure.entity.DocumentsVehiclesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("document_number");

                    b.Property<Guid>("DocumentStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("document_status_id");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<Guid>("TypeDocumentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("type_document_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.ToTable("documents_vehicles", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.drivers.Infrastructure.entity.DriversEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("license_number");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.drivers_vehicles.Infrastructure.entity.DriversVehiclesEntity", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)")
                        .HasColumnName("driver_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("DriverId", "VehicleId");

                    b.ToTable("drivers_vehicles", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.load_details.Infrastructure.entity.LoadDetailsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("DetailKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("detail_key");

                    b.Property<string>("DetailValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detail_value");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)")
                        .HasColumnName("load_id");

                    b.HasKey("Id");

                    b.ToTable("load_details", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.load_images.Infrastructure.entity.LoadImagesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)")
                        .HasColumnName("load_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("load_images", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.load_status_history.Infrastructure.entity.LoadStatusHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)")
                        .HasColumnName("load_id");

                    b.Property<Guid>("LoadStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("load_status_id");

                    b.HasKey("Id");

                    b.ToTable("load_status_history", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.loads.Infrastructure.entity.LoadsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("customer_id");

                    b.Property<string>("DestinationAddress")
                        .HasColumnType("text")
                        .HasColumnName("destination_address");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("destination_city_id");

                    b.Property<string>("DestinationCoords")
                        .HasColumnType("text")
                        .HasColumnName("destination_coords");

                    b.Property<Guid>("LoadStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("load_status_id");

                    b.Property<string>("OriginAddress")
                        .HasColumnType("text")
                        .HasColumnName("origin_address");

                    b.Property<Guid>("OriginCityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("origin_city_id");

                    b.Property<DateTime?>("PickupTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("pickup_time");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("TypeLoadId")
                        .HasColumnType("char(36)")
                        .HasColumnName("type_load_id");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("volume");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.HasIndex("TypeLoadId");

                    b.ToTable("loads", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.message_type.Infrastructure.entity.MessageTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("message_type", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.notification_type.Infrastructure.entity.NotificationTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("notification_type", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.notifications.Infrastructure.entity.NotificationsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<Guid>("NotificationTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("notification_type_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex("PersonId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.payment_providers.Infrastructure.entity.PaymentProvidersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("payment_providers", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.payment_statuses.Infrastructure.entity.PaymentStatusesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("payment_statuses", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.payments.Infrastructure.entity.PaymentsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountMoney")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount_money");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("PaymentProviderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("payment_provider_id");

                    b.Property<Guid>("PaymentStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("payment_status_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("char(36)")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("PaymentProviderId");

                    b.HasIndex("PaymentStatusId");

                    b.HasIndex("WalletId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.person_plans.Infrastructure.entity.PersonPlansEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("person_plans", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.person_roles.Infrastructure.entity.PersonRolesEntity", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id");

                    b.HasKey("PersonId", "RoleId");

                    b.ToTable("person_roles", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.person_status.Infrastructure.entity.PersonStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("person_status", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.person_transport.Infrastructure.entity.PersonTransportEntity", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.Property<Guid>("TransportCompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("transport_company_id");

                    b.HasKey("PersonId", "TransportCompanyId");

                    b.ToTable("person_transport", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.persons.Infrastructure.entity.PersonsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("id_num");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("PersonStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_status_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PersonStatusId");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.plans.Infrastructure.entity.PlansEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("billing_period");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.price_history.Infrastructure.entity.PriceHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.ToTable("price_history", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.ratings.Infrastructure.entity.RatingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RatedPersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rated_person_id");

                    b.Property<Guid>("RaterPersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rater_person_id");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.reason_disputes.Infrastructure.entity.ReasonDisputesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("reason_disputes", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.return_load_suggestions.Infrastructure.entity.ReturnLoadSuggestionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)")
                        .HasColumnName("load_id");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("score");

                    b.Property<Guid>("SuggestedLoadId")
                        .HasColumnType("char(36)")
                        .HasColumnName("suggested_load_id");

                    b.HasKey("Id");

                    b.ToTable("return_load_suggestions", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.roles.Infrastructure.entity.RolesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.states_regions.Infrastructure.entity.StatesRegionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("states_regions", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.status_bids.Infrastructure.entity.StatusBidsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("status_bids", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.status_trip.Infrastructure.entity.StatusTripEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("status_trip", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.subscription_status.Infrastructure.entity.SubscriptionStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("subscription_status", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.subscription_type.Infrastructure.entity.SubscriptionTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("subscription_type", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.subscriptions.Infrastructure.entity.SubscriptionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<Guid>("SubscriptionStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("subscription_status_id");

                    b.Property<Guid>("SubscriptionTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("subscription_type_id");

                    b.HasKey("Id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.transaction_types.Infrastructure.entity.TransactionTypesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("transaction_types", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.transport_companies.Infrastructure.entity.TransportCompaniesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("city_id");

                    b.Property<Guid>("CompaniesStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("companies_status_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CompaniesStatusId");

                    b.ToTable("transport_companies", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.travel_scale.Infrastructure.entity.TravelScaleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("LocationNote")
                        .HasColumnType("text")
                        .HasColumnName("location_note");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trip_id");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.ToTable("travel_scale", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.trip_assignments.Infrastructure.entity.TripAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentRoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assignment_role_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentRoleId");

                    b.HasIndex("PersonId");

                    b.HasIndex("TripId");

                    b.ToTable("trip_assignments", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.trip_checkpoints.Infrastructure.entity.TripCheckpointsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckpointTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("checkpoint_time");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.ToTable("trip_checkpoints", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.trip_status_history.Infrastructure.entity.TripStatusHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trip_id");

                    b.Property<Guid>("TripStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trip_status_id");

                    b.HasKey("Id");

                    b.ToTable("trip_status_history", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.trips.Infrastructure.entity.TripsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("destination_city_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("final_price");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)")
                        .HasColumnName("load_id");

                    b.Property<Guid>("OriginCityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("origin_city_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TripStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trip_status_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("DriverId");

                    b.HasIndex("LoadId");

                    b.HasIndex("OriginCityId");

                    b.HasIndex("TripStatusId");

                    b.HasIndex("VehicleId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.type_documents.Infrastructure.entity.TypeDocumentsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("type_documents", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.type_load.Infrastructure.entity.TypeLoadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("type_load", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.type_vehicles.Infrastructure.entity.TypeVehiclesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("type_vehicles", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.vehicles.Infrastructure.entity.VehiclesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("brand");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("chassis_number");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("color");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("plate");

                    b.Property<Guid>("TypeVehicleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("type_vehicle_id");

                    b.Property<Guid>("VehicleStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vehicle_status_id");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TypeVehicleId");

                    b.HasIndex("VehicleStatusId");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.vehicles_status.Infrastructure.entity.VehiclesStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("vehicles_status", (string)null);
                });

            modelBuilder.Entity("transporte.src.modules.auth_credentials.Infrastructure.entity.AuthCredentialsEntity", b =>
                {
                    b.HasOne("transporte.src.modules.persons.Infrastructure.entity.PersonsEntity", "Person")
                        .WithMany("AuthCredentials")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("transporte.src.modules.auth_sessions.Infrastructure.entity.AuthSessionsEntity", b =>
                {
                    b.HasOne("transporte.src.modules.persons.Infrastructure.entity.PersonsEntity", "Person")
                        .WithMany("AuthSessions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("transporte.src.modules.bids.Infrastructure.entity.BidsEntity", b =>
                {
                    b.HasOne("transporte.src.modules.drivers.Infrastructure.entity.DriversEntity", "Driver")
                        .WithMany("Bids")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.loads.Infrastructure.entity.LoadsEntity", "Load")
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.status_bids.Infrastructure.entity.StatusBidsEntity", "BidStatus")
                        .WithMany("Bids")
                        .HasForeignKey("StatusBidsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.vehicles.Infrastructure.entity.VehiclesEntity", "Vehicle")
                        .WithMany("Bids")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BidStatus");

                    b.Navigation("Driver");

                    b.Navigation("Load");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("transporte.src.modules.chat_messages.Infrastructure.entity.ChatMessagesEntity", b =>
                {
                    b.HasOne("transporte.src.modules.chat_rooms.Infrastructure.entity.ChatRoomsEntity", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.persons.Infrastructure.entity.PersonsEntity", "Sender")
                        .WithMany("SentChatMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("transporte.src.modules.chat_participants.Infrastructure.entity.ChatParticipantsEntity", b =>
                {
                    b.HasOne("transporte.src.modules.chat_rooms.Infrastructure.entity.ChatRoomsEntity", "ChatRoom")
                        .WithMany("Participants")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.persons.Infrastructure.entity.PersonsEntity", "Person")
                        .WithMany("ChatParticipations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("transporte.src.modules.chat_rooms.Infrastructure.entity.ChatRoomsEntity", b =>
                {
                    b.HasOne("transporte.src.modules.trips.Infrastructure.entity.TripsEntity", "Trip")
                        .WithMany("ChatRooms")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("transporte.src.modules.credit_transactions.Infrastructure.entity.CreditTransactionsEntity", b =>
                {
                    b.HasOne("transporte.src.modules.credit_wallet.Infrastructure.entity.CreditWalletEntity", "CreditWallet")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("CreditWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.transaction_types.Infrastructure.entity.TransactionTypesEntity", "TransactionType")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreditWallet");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("transporte.src.modules.credit_wallet.Infrastructure.entity.CreditWalletEntity", b =>
                {
                    b.HasOne("transporte.src.modules.persons.Infrastructure.entity.PersonsEntity", "Person")
                        .WithMany("CreditWallets")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("transporte.src.modules.drivers.Infrastructure.entity.DriversEntity", b =>
                {
                    b.HasOne("transporte.src.modules.persons.Infrastructure.entity.PersonsEntity", "Person")
                        .WithMany("Drivers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("transporte.src.modules.loads.Infrastructure.entity.LoadsEntity", b =>
                {
                    b.HasOne("transporte.src.modules.persons.Infrastructure.entity.PersonsEntity", "Customer")
                        .WithMany("LoadsAsCustomer")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.cities_municipalities.Infrastructure.entity.CitiesMunicipalitiesEntity", "DestinationCity")
                        .WithMany("LoadsAsDestination")
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.cities_municipalities.Infrastructure.entity.CitiesMunicipalitiesEntity", "OriginCity")
                        .WithMany("LoadsAsOrigin")
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.type_load.Infrastructure.entity.TypeLoadEntity", "TypeLoad")
                        .WithMany("Loads")
                        .HasForeignKey("TypeLoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");

                    b.Navigation("TypeLoad");
                });

            modelBuilder.Entity("transporte.src.modules.notifications.Infrastructure.entity.NotificationsEntity", b =>
                {
                    b.HasOne("transporte.src.modules.notification_type.Infrastructure.entity.NotificationTypeEntity", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.persons.Infrastructure.entity.PersonsEntity", "Person")
                        .WithMany("Notifications")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotificationType");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("transporte.src.modules.payments.Infrastructure.entity.PaymentsEntity", b =>
                {
                    b.HasOne("transporte.src.modules.payment_providers.Infrastructure.entity.PaymentProvidersEntity", "PaymentProvider")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.payment_statuses.Infrastructure.entity.PaymentStatusesEntity", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.credit_wallet.Infrastructure.entity.CreditWalletEntity", "Wallet")
                        .WithMany("Payments")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentProvider");

                    b.Navigation("PaymentStatus");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("transporte.src.modules.persons.Infrastructure.entity.PersonsEntity", b =>
                {
                    b.HasOne("transporte.src.modules.transport_companies.Infrastructure.entity.TransportCompaniesEntity", "Company")
                        .WithMany("Persons")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("transporte.src.modules.person_status.Infrastructure.entity.PersonStatusEntity", "PersonStatus")
                        .WithMany("Persons")
                        .HasForeignKey("PersonStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("PersonStatus");
                });

            modelBuilder.Entity("transporte.src.modules.transport_companies.Infrastructure.entity.TransportCompaniesEntity", b =>
                {
                    b.HasOne("transporte.src.modules.cities_municipalities.Infrastructure.entity.CitiesMunicipalitiesEntity", "City")
                        .WithMany("TransportCompanies")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.companies_status.Infrastructure.entity.CompaniesStatusEntity", "CompaniesStatus")
                        .WithMany("TransportCompanies")
                        .HasForeignKey("CompaniesStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("CompaniesStatus");
                });

            modelBuilder.Entity("transporte.src.modules.trip_assignments.Infrastructure.entity.TripAssignmentEntity", b =>
                {
                    b.HasOne("transporte.src.modules.assignment_role.Infrastructure.entity.AssignmentEntity", "AssignmentRole")
                        .WithMany("TripAssignments")
                        .HasForeignKey("AssignmentRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.persons.Infrastructure.entity.PersonsEntity", "Person")
                        .WithMany("TripAssignments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.trips.Infrastructure.entity.TripsEntity", "Trip")
                        .WithMany("TripAssignments")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignmentRole");

                    b.Navigation("Person");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("transporte.src.modules.trips.Infrastructure.entity.TripsEntity", b =>
                {
                    b.HasOne("transporte.src.modules.cities_municipalities.Infrastructure.entity.CitiesMunicipalitiesEntity", "DestinationCity")
                        .WithMany("TripsAsDestination")
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.drivers.Infrastructure.entity.DriversEntity", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.loads.Infrastructure.entity.LoadsEntity", "Load")
                        .WithMany("Trips")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.cities_municipalities.Infrastructure.entity.CitiesMunicipalitiesEntity", "OriginCity")
                        .WithMany("TripsAsOrigin")
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.status_trip.Infrastructure.entity.StatusTripEntity", "TripStatus")
                        .WithMany("Trips")
                        .HasForeignKey("TripStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.vehicles.Infrastructure.entity.VehiclesEntity", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationCity");

                    b.Navigation("Driver");

                    b.Navigation("Load");

                    b.Navigation("OriginCity");

                    b.Navigation("TripStatus");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("transporte.src.modules.vehicles.Infrastructure.entity.VehiclesEntity", b =>
                {
                    b.HasOne("transporte.src.modules.transport_companies.Infrastructure.entity.TransportCompaniesEntity", "Company")
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.type_vehicles.Infrastructure.entity.TypeVehiclesEntity", "TypeVehicle")
                        .WithMany("Vehicles")
                        .HasForeignKey("TypeVehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("transporte.src.modules.vehicles_status.Infrastructure.entity.VehiclesStatusEntity", "VehicleStatus")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("TypeVehicle");

                    b.Navigation("VehicleStatus");
                });

            modelBuilder.Entity("transporte.src.modules.assignment_role.Infrastructure.entity.AssignmentEntity", b =>
                {
                    b.Navigation("TripAssignments");
                });

            modelBuilder.Entity("transporte.src.modules.chat_rooms.Infrastructure.entity.ChatRoomsEntity", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("transporte.src.modules.cities_municipalities.Infrastructure.entity.CitiesMunicipalitiesEntity", b =>
                {
                    b.Navigation("LoadsAsDestination");

                    b.Navigation("LoadsAsOrigin");

                    b.Navigation("TransportCompanies");

                    b.Navigation("TripsAsDestination");

                    b.Navigation("TripsAsOrigin");
                });

            modelBuilder.Entity("transporte.src.modules.companies_status.Infrastructure.entity.CompaniesStatusEntity", b =>
                {
                    b.Navigation("TransportCompanies");
                });

            modelBuilder.Entity("transporte.src.modules.credit_wallet.Infrastructure.entity.CreditWalletEntity", b =>
                {
                    b.Navigation("CreditTransactions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("transporte.src.modules.drivers.Infrastructure.entity.DriversEntity", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("transporte.src.modules.loads.Infrastructure.entity.LoadsEntity", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("transporte.src.modules.notification_type.Infrastructure.entity.NotificationTypeEntity", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("transporte.src.modules.payment_providers.Infrastructure.entity.PaymentProvidersEntity", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("transporte.src.modules.payment_statuses.Infrastructure.entity.PaymentStatusesEntity", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("transporte.src.modules.person_status.Infrastructure.entity.PersonStatusEntity", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("transporte.src.modules.persons.Infrastructure.entity.PersonsEntity", b =>
                {
                    b.Navigation("AuthCredentials");

                    b.Navigation("AuthSessions");

                    b.Navigation("ChatParticipations");

                    b.Navigation("CreditWallets");

                    b.Navigation("Drivers");

                    b.Navigation("LoadsAsCustomer");

                    b.Navigation("Notifications");

                    b.Navigation("SentChatMessages");

                    b.Navigation("TripAssignments");
                });

            modelBuilder.Entity("transporte.src.modules.status_bids.Infrastructure.entity.StatusBidsEntity", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("transporte.src.modules.status_trip.Infrastructure.entity.StatusTripEntity", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("transporte.src.modules.transaction_types.Infrastructure.entity.TransactionTypesEntity", b =>
                {
                    b.Navigation("CreditTransactions");
                });

            modelBuilder.Entity("transporte.src.modules.transport_companies.Infrastructure.entity.TransportCompaniesEntity", b =>
                {
                    b.Navigation("Persons");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("transporte.src.modules.trips.Infrastructure.entity.TripsEntity", b =>
                {
                    b.Navigation("ChatRooms");

                    b.Navigation("TripAssignments");
                });

            modelBuilder.Entity("transporte.src.modules.type_load.Infrastructure.entity.TypeLoadEntity", b =>
                {
                    b.Navigation("Loads");
                });

            modelBuilder.Entity("transporte.src.modules.type_vehicles.Infrastructure.entity.TypeVehiclesEntity", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("transporte.src.modules.vehicles.Infrastructure.entity.VehiclesEntity", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("transporte.src.modules.vehicles_status.Infrastructure.entity.VehiclesStatusEntity", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
